/* ------------------------------------------------------------------ */
/* WiFiSense Lab — dataset export (Phase 3).                           */
/* CSV + JSON today; NPZ / Parquet hooks arrive with the Python        */
/* processor (Phase 9). Every export carries an explicit provenance    */
/* block so downstream tools can never mistake simulated frames for    */
/* hardware measurements.                                              */
/* ------------------------------------------------------------------ */

import type {
  DatasetMeta,
  DatasetSample,
  SensorSim,
  SimConfig,
  SourceMode,
  TelemetryPoint,
} from "../types";

export interface ExportMeta {
  platform: "WiFiSense Lab";
  format: 1;
  source: SourceMode;
  provenance: string;
  sensorId: string;
  sensorName: string;
  room: string;
  seed: number;
  sampleRateHz: number;
  subcarriers: number;
  frames: number;
  exportedAtISO: string;
}

export function buildMeta(s: SensorSim, cfg: SimConfig, mode: SourceMode): ExportMeta {
  return {
    platform: "WiFiSense Lab",
    format: 1,
    source: mode,
    provenance:
      mode === "simulation"
        ? "SYNTHETIC CSI generated by the deterministic simulation engine — not hardware measurements"
        : "Live hardware stream",
    sensorId: s.id,
    sensorName: s.name,
    room: s.roomName,
    seed: cfg.seed,
    sampleRateHz: cfg.sampleRate,
    subcarriers: cfg.subcarriers,
    frames: s.buffer.length,
    exportedAtISO: new Date().toISOString(),
  };
}

const CSV_HEADER = "t_s,amplitude,phase_rad,rssi_dbm,variance,motion_score";

export function toCSV(buffer: TelemetryPoint[]): string {
  const lines = [CSV_HEADER];
  for (const p of buffer) {
    lines.push(
      [
        p.t.toFixed(3),
        p.amp.toFixed(6),
        p.phase.toFixed(6),
        p.rssi.toFixed(2),
        p.variance.toExponential(4),
        p.score.toFixed(4),
      ].join(","),
    );
  }
  return lines.join("\n");
}

export function toJSON(meta: ExportMeta, buffer: TelemetryPoint[]): string {
  return JSON.stringify(
    {
      meta,
      columns: ["t_s", "amplitude", "phase_rad", "rssi_dbm", "variance", "motion_score"],
      rows: buffer.map((p) => [
        +p.t.toFixed(3),
        +p.amp.toFixed(6),
        +p.phase.toFixed(6),
        +p.rssi.toFixed(2),
        +p.variance.toExponential(4),
        +p.score.toFixed(4),
      ]),
    },
    null,
    2,
  );
}

/** RFC-4180-ish escape for label fields used by later dataset exports. */
export function csvEscape(v: string): string {
  return /[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
}

/* ----------------------- dataset export (Phase 7) ------------------ */

const DATASET_HEADER = "t_s,sensor_id,rssi_dbm,amplitude,phase_rad,variance,motion_score";

export function datasetToCSV(meta: DatasetMeta, samples: DatasetSample[]): string {
  const lines = [DATASET_HEADER];
  for (const s of samples) {
    lines.push(
      [
        s.t.toFixed(3),
        csvEscape(s.sensorId),
        s.rssi.toFixed(2),
        s.amp.toFixed(6),
        s.phase.toFixed(6),
        s.variance.toExponential(4),
        s.score.toFixed(4),
      ].join(","),
    );
  }
  // Append label markers as comment lines for traceability.
  for (const l of meta.labels) {
    lines.push(`# label @ ${l.t.toFixed(3)}s :: ${csvEscape(l.label)}`);
  }
  return lines.join("\n");
}

export function datasetToJSON(meta: DatasetMeta, samples: DatasetSample[]): string {
  return JSON.stringify(
    {
      meta: {
        ...meta,
        provenance:
          meta.source === "simulation"
            ? "SYNTHETIC CSI generated by the deterministic simulation engine — not hardware measurements"
            : "Live hardware stream",
      },
      columns: ["t_s", "sensor_id", "rssi_dbm", "amplitude", "phase_rad", "variance", "motion_score"],
      rows: samples.map((s) => [
        +s.t.toFixed(3),
        s.sensorId,
        +s.rssi.toFixed(2),
        +s.amp.toFixed(6),
        +s.phase.toFixed(6),
        +s.variance.toExponential(4),
        +s.score.toFixed(4),
      ]),
      labels: meta.labels,
    },
    null,
    2,
  );
}

export function sanitizeFilename(name: string): string {
  return name.replace(/[^a-z0-9._-]+/gi, "_").replace(/_{2,}/g, "_").slice(0, 64) || "export";
}

export function downloadText(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = sanitizeFilename(filename);
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
